<field:backEnd itemname="后端开发" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:backEnd>
<field:webUI itemname="UI设计师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:webUI>
<field:proManager itemname="产品经理" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:proManager>
<field:site itemname="存储位置" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:site>
<field:colors itemname="色系" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="无色（#999999）,红色（#ee1413）,橙色（#eead15）,黄色（#eced15）,绿色（#14b92f）,青色（#3bdebf）,蓝色（#3c75de）,紫色（#c93bdf）"  maxlength="250" page="">
</field:colors>
<field:htmlfile itemname="html附件" autofield="1" notsend="0" type="addon" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:htmlfile>
<field:fontend itemname="前端开发" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="胥严方,孙利利,钱俊杰,张中乐"  maxlength="250" page="">
</field:fontend>
<field:info itemname="图文介绍" autofield="1" notsend="0" type="textdata" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:info>

<field:website itemname="上线网址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:website>

<field:fieldtype itemname="文件格式" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="html,图片"  maxlength="250" page="">
</field:fieldtype>
