<field:fontEnd itemname="前端开发" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fontEnd>
<field:backEnd itemname="后端开发" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:backEnd>
<field:webUI itemname="UI设计师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:webUI>
<field:proManager itemname="产品经理" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:proManager>
<field:site itemname="存储位置" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:site>
<field:colors itemname="色系" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="无色（#999999）,红色（#ee1413）,橙色（#eead15）,黄色（#eced15）,绿色（#14b92f）,青色（#3bdebf）,蓝色（#3c75de）,紫色（#c93bdf）"  maxlength="250" page="">
</field:colors>

<field:imginfo itemname="图文介绍" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:imginfo>
