<div class="img-item fl">
							<a class="img" href="[field:arcurl/]" target="_blank"><img class="lazy" alt="[field:title function='html2text(@me)'/]" src="[field:litpic/]" style="display: inline;"></a>
							<!--灵感vip-->
							<div class="img-pos">
								<a href="[field:htmlfile /]" target="_blank">
									<div class="free-download"><i></i><span>免费下载</span></div>
								</a>
								<div class="img-opacity"></div>
								<a href="[field:arcurl/]" target="_blank">
									<div class="img-but" target="_blank">
										<p>[field:title/]</p>
									</div>
								</a>
							</div>
						</div>