
<field:hdimg itemname="高清图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hdimg>
<field:device itemname="设备" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="电脑端,移动端"  maxlength="250" page="">
</field:device>
<field:type itemname="类型" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="列表,标题,分页,导航,页头,页尾,表单,表格,弹窗,登录,按钮,字段,其他"  maxlength="250" page="">
</field:type>
<field:code itemname="代码" autofield="1" notsend="0" type="textdata" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:code>

