<?php
$z[0]=Array("field","",93,122);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n					<div class=\"img-show fl\">\n						<div class=\"img\">\n							<a href=\"[field:arcurl /]\" target=\"_blank\"><img class=\"lazy\" alt=\"[field:title function='html2text(@me)'/]\" width=\"380\" height=\"572\" src=\"[field:picname /]\"/></a>\n						</div>\n						<!--灵感vip-->\n						<div class=\"img-pos\">\n							<a href=\"[field:htmlfile /]\" target=\"_blank\">\n								<div class=\"free-download\"><i></i><span>免费下载</span></div>\n							</a>\n							<a href=\"[dede:field name='phpurl'/]/stow.php?aid=[dede:field.id/]\">\n								<div class=\"collect\" data-id=\"27625\" data-status=\"0\"><i></i>收藏</div>\n							</a>\n							<div class=\"img-opacity\"></div>\n							<a href=\"[field:arcurl /]\" target=\"_blank\">\n								<div class=\"img-but\" target=\"_blank\">\n									<p>[field:title /]</p>\n								</div>\n							</a>\n						</div>\n					</div>\n					",252,1153);
$z[1][4]['titlelen']="60";
$z[1][4]['row']="8";
$z[1][4]['channelid']="17";
$z[1][4]['typeid']="4";
$z[2]=Array("field","",1178,1206);
$z[2][4]['name']="typeurl";

?>