<field:htmlfile itemname="html附件" autofield="1" notsend="0" type="addon" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:htmlfile>
<field:largeimg itemname="高清大图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:largeimg>
<field:layout itemname="布局" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="通栏,居中,响应式,移动端"  maxlength="250" page="">
</field:layout>
<field:school itemname="院校" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="大学,中学,小学"  maxlength="250" page="">
</field:school>
<field:colors itemname="所属色系" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="无色,红色,橙色,黄色,绿色,青色,蓝色,紫色"  maxlength="250" page="">
</field:colors>
<field:website itemname="上线网址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:website>
<field:webui itemname="UI设计师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:webui>
<field:fontend itemname="前端开发" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="胥严方,孙利利,钱俊杰,张中乐"  maxlength="250" page="">
</field:fontend>
<field:backend itemname="后端开发" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:backend>
<field:promanager itemname="产品经理" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:promanager>
<field:info itemname="备注介绍" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default="暂无"  maxlength="250" page="">
</field:info>
