<li [field:global name="autoindex" runphp="yes"]if(@me%3==0)@me='class="mrnone"'; else @me="";[/field:global]>
            <div><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" width="278" height="245"></a></div>
            <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
            <p>[field:description function="cn_substr(@me,150)"/]</p>
            <span class="more"><a href="[field:arcurl/]">浏览案例</a></span>
        </li>