<?php
$z[0]=Array("global","if(@me%3==0)@me='class=\"mrnone\"'; else @me=\"\";",4,109);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",138,153);
$z[2]=Array("title","",162,176);
$z[3]=Array("litpic","",188,203);
$z[4]=Array("arcurl","",267,282);
$z[5]=Array("title","",291,305);
$z[6]=Array("title","",307,321);
$z[7]=Array("description","",347,397);
$z[7][4]['function']="cn_substr(@me,150)";
$z[8]=Array("arcurl","",443,458);

?>