<?php
$z[0]=Array("field","",93,122);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n					<div class=\"img-show fl\">\n						<div class=\"img\">\n							<a href=\"[field:arcurl /]\" target=\"_blank\"><img class=\"lazy\" alt=\"[field:title function='html2text(@me)'/]\" width=\"380\" height=\"572\" src=\"[field:picname /]\"/></a>\n						</div>\n						<!--灵感vip-->\n						<div class=\"img-pos\">\n							<a href=\"http://888pic.com/?m=download&id=27625\" target=\"_blank\">\n								<div class=\"free-download\"><i></i><span>免费下载</span></div>\n							</a>\n							<a href=\"javascript:;\">\n								<div class=\"collect\" data-id=\"27625\" data-status=\"0\"><i></i>收藏</div>\n							</a>\n							<div class=\"img-opacity\"></div>\n							<a href=\"[field:arcurl /]\" target=\"_blank\">\n								<div class=\"img-but\" target=\"_blank\">\n									<p>[field:title /]</p>\n								</div>\n							</a>\n						</div>\n					</div>\n					",252,1101);
$z[1][4]['titlelen']="60";
$z[1][4]['row']="8";
$z[2]=Array("field","",1126,1154);
$z[2][4]['name']="typeurl";

?>