<field:高清图 itemname="高清图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:高清图>
<field:设备 itemname="设备" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="电脑端,移动端"  maxlength="250" page="">
</field:设备>
<field:类型 itemname="类型" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="列表,标题,分布,导航,表单,页头,页尾,表格,弹窗,登录,按钮,其他"  maxlength="250" page="">
</field:类型>
