<div class="img-show fl">
						<div class="img">
							<a href="[field:arcurl /]" target="_blank"><img class="lazy" alt="[field:title function='html2text(@me)'/]" src="[field:picname /]"/></a>
						</div>
						<div class="img-pos">
							<a href="[field:htmlfile /]" target="_blank">
								<div class="free-download"><i></i><span>免费下载</span></div>
							</a>
							<a href="[dede:field name='phpurl'/]/stow.php?aid=[dede:field.id/]">
								<div class="collect" data-id="[field:id/]"><i></i>收藏</div>
							</a>
							<div class="img-opacity"></div>
							<a href="[field:arcurl /]" target="_blank">
								<div class="img-but" target="_blank">
									<p>[field:title /]</p>
								</div>
							</a>
						</div>
					</div>