<li>
               <a href="[field:phpurl/]/plus/guestbook.php" class="user_img fn-left">
                   <img src="[field:phpurl/]/plus/guestbook/images/[field:face /].gif" alt="" width="30"
                                                              height="30" /></a>
 
                <div class="cnt_sub_txt fn-right">
                    <p>[field:uname /]
                        [field:ip /]</p>
 
                    <p>
                       <a href="[field:phpurl/]/plus/guestbook.php" alt="[field:msg function="cn_substr('@me',60)"/]"> [field:msg function="cn_substr('@me',50)"/]</a></p>
                </div>
            </li>