
    <m:item name='软件' ischannel='1' link='content_i_list.php?channelid=3' linkadd='soft_add.php?channelid=3' channelid='3' rank='' target='main' />
  <m:item name='门户' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
