
    <m:item name='项目进度' ischannel='1' link='content_sg_list.php?channelid=-18' linkadd='archives_sg_add.php?channelid=-18' channelid='-18' rank='' target='main' />
  <m:item name='门户' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='模块' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add.php?channelid=18' channelid='18' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
