<div class="img-show fl">
							<div class="img">
								<a href="[field:arcurl/]" target="_blank"><img class="lazy" data-original="http://pic.888pic.com/16/07/08/433888piCZUz.jpg-0.jpg!w380" alt="淘宝中国风七夕情人节店铺模板" width="380" height="572" src="[field:imges/]" style="display: inline;"></a>
							</div>

							<!--灵感vip-->
							<div class="img-pos">
								<a href="http://888pic.com/?m=download&id=943" target="_blank">
									<!--<div class="free-download"><i></i><span>免费下载</span></div>-->
									<div class="free-download"><i></i><span>免费下载</span></div>
								</a>
								<a href="javascript:;">
									<div class="collect" data-id="943" data-status="0"><i></i>收藏</div>
								</a>
								<div class="img-opacity"></div>
								<a href="http://888pic.com/sucai/943.html" target="_blank">
									<div class="img-but" target="_blank">
										<p>[field:title/]</p>
									</div>
								</a>
							</div>
						</div>