
<field:fontEnd itemname="前端开发" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fontEnd>

<field:backEnd itemname="后端开发" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:backEnd>

<field:webUI itemname="UI设计师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:webUI>

<field:proManager itemname="产品经理" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:proManager>
