<?php
$z[0]=Array("global","",459,484);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n				<a href=\"[field:typeurl/]\" [field:rel/] target=\"_blank\" class=\"headercom\">[field:typename/]</a>\r\n				",537,791);
$z[1][4]['type']="top";
$z[1][4]['row']="6";
$z[1][4]['currentstyle']="<a class='headercom' style='color:#ff9100;' href='~typelink~' ~rel~>~typename~</a>";
$z[2]=Array("global","",1029,1054);
$z[2][4]['name']="cfg_cmsurl";

?>