<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",199,228);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",377,409);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",478,510);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",574,606);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",735,770);
$z[7][4]['filename']="head.htm";
$z[8]=Array("php"," AddFilter(18,1,'device'); ",939,987);
$z[9]=Array("php"," AddFilter(18,1,'type'); ",1258,1304);
$z[10]=Array("list","\r\n						<div class=\"img-item fl\">\r\n							<a class=\"img\" href=\"[field:arcurl/]\" target=\"_blank\"><img class=\"lazy\" alt=\"[field:title function='html2text(@me)'/]\" src=\"[field:litpic/]\" style=\"display: inline;\"></a>\r\n						</div>\r\n						",1487,1758);
$z[10][4]['pagesize']="16";
$z[11]=Array("global","",3000,3032);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("include","",3059,3096);
$z[12][4]['filename']="footer.htm";
$z[13]=Array("global","",3112,3144);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("field","",4357,4384);
$z[14][4]['name']="typeid";

?>