<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",199,228);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",377,409);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",478,510);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",574,606);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",643,678);
$z[7][4]['filename']="head.htm";
$z[8]=Array("php"," AddFilter(17,1,'layout'); ",785,833);
$z[9]=Array("php"," AddFilter(17,1,'school'); ",1107,1155);
$z[10]=Array("php"," AddFilter(17,1,'colors'); ",1427,1475);
$z[11]=Array("php"," AddFilter(17,1,'fontend'); ",1738,1787);
$z[12]=Array("list","\n						<div class=\"img-show fl\">\n							<div class=\"img\">\n								<a href=\"[field:arcurl/]\" target=\"_blank\"><img class=\"lazy\" alt=\"[field:title function='html2text(@me)'/]\" src=\"[field:litpic/]\" style=\"display: inline;\"></a>\n							</div>\n\n							<!--灵感vip-->\n							<div class=\"img-pos\">\n								<a href=\"[field:htmlfile /]\" target=\"_blank\">\n									<div class=\"free-download\"><i></i><span>免费下载</span></div>\n								</a>\n								<div class=\"img-opacity\"></div>\n								<a href=\"[field:arcurl/]\" target=\"_blank\">\n									<div class=\"img-but\" target=\"_blank\">\n										<p>[field:title/]</p>\n									</div>\n								</a>\n							</div>\n						</div>\n						",1886,2590);
$z[12][4]['pagesize']="16";
$z[13]=Array("pagelist","",2649,2720);
$z[13][4]['listitem']="info,index,end,pre,next,pageno";
$z[13][4]['listsize']="5";
$z[14]=Array("global","",3870,3902);
$z[14][4]['name']="cfg_templets_skin";
$z[15]=Array("include","",3929,3966);
$z[15][4]['filename']="footer.htm";
$z[16]=Array("global","",3982,4014);
$z[16][4]['name']="cfg_templets_skin";

?>